version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
