site_name: universalasync
site_description: A library to help automate the creation of universal python libraries
site_url: https://universalasync.bitcart.ai
repo_url: https://github.com/bitcart/universalasync
repo_name: bitcart/universalasync
site_dir: site
watch: [docs, mkdocs.yml, universalasync]
copyright: "Copyright &copy; 2021 MrNaif2018"
hooks:
  - docs/hooks.py

docs_dir: docs/content

theme:
  name: material
  custom_dir: docs
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference

nav:
  - Home: index.md
  - API Reference: api.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            backlinks: tree
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            heading_level: 2
            line_length: 88
            merge_init_into_class: true
            parameter_headings: true
            type_parameter_headings: true
            relative_crossrefs: true
            scoped_crossrefs: true
            separate_signature: true
            show_bases: false
            show_inheritance_diagram: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_signature_type_parameters: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true
  - typeset

markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist
  - toc:
      permalink: true

extra_css:
  - css/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bitcart/universalasync
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/universalasync
